spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 21936281134-1j5c5vq0fsrdl0q24g8udb3k11q2o0ir.apps.googleusercontent.com
            clientSecret: N85zWq6IiDHQoayFTOy-jTmv
